version: 2
jobs:
  build_35: &DEFAULT
     machine:
       # Don't use 2018 image: https://discuss.circleci.com/t/24639/18
       image: circleci/classic:201711-01
       docker_layer_caching: true
     environment:
      CONDA_ENV_PY_VERSION: 3.5.4
     steps:
       - checkout
       - run:
          name: Create virtual env
          command: |
            # Get rid of pyenv stuff
            sudo rm -rf .pyenv/ /opt/circleci/.pyenv/

            # Download and install miniconda
            curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  > miniconda.sh
            bash miniconda.sh -b -p $HOME/miniconda

            # Create an anaconda virtualenv for ${CONDA_ENV_PY_VERSION} and make that the default python interpreter
            echo ". /home/circleci/miniconda/etc/profile.d/conda.sh" >> $BASH_ENV
            echo "conda deactivate; conda activate kedro-airflow" >> $BASH_ENV
            . /home/circleci/miniconda/etc/profile.d/conda.sh
            conda create --name kedro-airflow python=${CONDA_ENV_PY_VERSION} -y
            source $BASH_ENV
       - run:
          name: Pip install dependencies
          command: |
            make install-pip-setuptools
            pip install git+https://github.com/quantumblacklabs/kedro
            export AIRFLOW_GPL_UNIDECODE=yes
            pip install -r requirements.txt
            pip install -r test_requirements.txt
       - run:
          name: Run pylint and flake8
          command: |
            make lint
       - run:
          name: Run tests
          command: |
            make test
       - run:
          name: Run all end to end tests
          command: |
            make e2e-tests
       - run:
          name: Check for legal compliance
          command: |
            make legal
       - run:
          name: Publish to PyPI
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              make package
              python -m pip install twine -U
              python -m twine upload --repository-url ${TWINE_REPOSITORY_URL} dist/*
            fi
  build_36:
    <<: *DEFAULT
    environment:
      CONDA_ENV_PY_VERSION: 3.6
  build_37:
    <<: *DEFAULT
    environment:
      CONDA_ENV_PY_VERSION: 3.7
  license_checker:
    docker:
      - image: quantumblacklabs/kedro_builder:3.6
    steps:
      - checkout
      - run:
          name: Create conda environment
          command: |
            echo ". /home/circleci/miniconda/etc/profile.d/conda.sh" > $BASH_ENV
            echo "conda deactivate; conda activate license_checker" >> $BASH_ENV
            . /home/circleci/miniconda/etc/profile.d/conda.sh
            conda create --name=license_checker python=3.6 -y
            source $BASH_ENV
      - run:
          name: Install Kedro-Docker
          command: make install
      - run:
          name: Check package licenses
          command: |
            pip install pip-licenses
            chmod +x /home/circleci/project/tools/license_checker.py
            /home/circleci/project/tools/license_checker.py

workflows:
  version: 2
  regular:
    jobs:
      - build_35
      - build_36
      - build_37
      - license_checker
