version: 2
jobs:
  build:
     machine:
       # Don't use 2018 image: https://discuss.circleci.com/t/24639/18
       image: circleci/classic:201711-01
       docker_layer_caching: true
     steps:
       - checkout
       - run:
          name: Create virtual env
          command: |
            # Get rid of pyenv stuff
            sudo rm -rf .pyenv/ /opt/circleci/.pyenv/

            # Download and install miniconda
            curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  > miniconda.sh
            sudo bash miniconda.sh -b -p $HOME/miniconda

            # Create an anaconda virtualenv for python 3.5.2 and make that the default python interpreter
            echo ". /home/circleci/miniconda/etc/profile.d/conda.sh" >> $BASH_ENV
            echo "conda deactivate; conda activate ked" >> $BASH_ENV
            . /home/circleci/miniconda/etc/profile.d/conda.sh
            conda create --name ked python=3.5.2 -y
            source $BASH_ENV
       - run:
          name: Pip install dependencies
          command: |
            make install-pip-setuptools
            pip install "kedro>=0.dev0"
            export AIRFLOW_GPL_UNIDECODE=yes
            pip install -r requirements.txt -U
            pip install -r test_requirements.txt -U
       - run:
          name: Run pylint and flake8
          command: |
            make lint
       - run:
          name: Run tests
          command: |
            make test
       - run:
          name: Run all end to end tests
          command: |
            make e2e-tests

workflows:
  version: 2
  regular:
    jobs:
      - build
